# Atividade 3 — Análise das áreas de formação

**Aluno:** Júlio

**Fonte dos dados:** IBGE — Censo Demográfico

## 1. Importar a biblioteca

In [1]:
import pandas as pd

## 2. Ler o arquivo original

In [2]:
arquivo = "Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"
bruto = pd.read_excel(arquivo, engine="openpyxl", header=None)
bruto

                                                    0  ...         9
0   Tabela 10063 - Pessoas com nível superior comp...  ...       NaN
1        Brasil, Grande Região e Unidade da Federação  ...       NaN
2                                                 NaN  ...  Mulheres
3                                              Brasil  ...   6401723
4                                               Norte  ...    458616
5                                            Nordeste  ...   1458181
6                                             Sudeste  ...   2884108
7                                                 Sul  ...   1007718
8                                        Centro-Oeste  ...    593101
9                                            Rondônia  ...     49622
10                                               Acre  ...     24258
11                                           Amazonas  ...     91249
12                                            Roraima  ...     18098
13                                               Pará  ...    190270
14                                              Amapá  ...     26960
15                                          Tocantins  ...     58158
16                                           Maranhão  ...    165555
17                                              Piauí  ...    102457
18                                              Ceará  ...    229996
19                                Rio Grande do Norte  ...    107161
20                                            Paraíba  ...    120837
21                                         Pernambuco  ...    224362
22                                            Alagoas  ...     86911
23                                            Sergipe  ...     66376
24                                              Bahia  ...    354528
25                                       Minas Gerais  ...    674521
26                                     Espírito Santo  ...    131544
27                                     Rio de Janeiro  ...    466399
28                                          São Paulo  ...   1611645
29                                             Paraná  ...    403280
30                                     Santa Catarina  ...    265964
31                                  Rio Grande do Sul  ...    338472
32                                 Mato Grosso do Sul  ...    101443
33                                        Mato Grosso  ...    114069
34                                              Goiás  ...    232052
35                                   Distrito Federal  ...    145538
36                    Fonte: IBGE - Censo Demográfico  ...       NaN

[37 rows x 10 columns]

## 3. Selecionar as linhas das 5 grandes regiões

Na planilha, a linha 4 (índice 3) é o Brasil, as linhas 5 a 9 (índices 4 a 8) são as cinco grandes regiões, depois vêm os estados e por fim a linha da fonte. Vamos usar `iloc` para pegar só as linhas das regiões.

In [3]:
dados = bruto.iloc[4:9].copy()
dados

              0         1        2        3  ...       6        7       8        9
4         Norte   1525166   590558   934609  ...   76601   599785  141169   458616
5      Nordeste   4748933  1744994  3003939  ...  231395  1822087  363905  1458181
6       Sudeste  12828829  5391638  7437191  ...  739247  3652397  768288  2884108
7           Sul   4338861  1768855  2570005  ...  235543  1256291  248574  1007718
8  Centro-Oeste   2412502   982489  1430013  ...  115834   749148  156048   593101

[5 rows x 10 columns]

## 4. Definir os nomes das colunas

In [4]:
dados.columns = [
    "regiao",
    "total_superior", "homens_superior", "mulheres_superior",
    "total_ctem", "homens_ctem", "mulheres_ctem",
    "total_bem_estar", "homens_bem_estar", "mulheres_bem_estar",
]
dados

         regiao total_superior  ... homens_bem_estar mulheres_bem_estar
4         Norte        1525166  ...           141169             458616
5      Nordeste        4748933  ...           363905            1458181
6       Sudeste       12828829  ...           768288            2884108
7           Sul        4338861  ...           248574            1007718
8  Centro-Oeste        2412502  ...           156048             593101

[5 rows x 10 columns]

## 5. Converter as colunas numéricas

In [5]:
colunas_numericas = [
    "total_superior", "homens_superior", "mulheres_superior",
    "total_ctem", "homens_ctem", "mulheres_ctem",
    "total_bem_estar", "homens_bem_estar", "mulheres_bem_estar",
]

for coluna in colunas_numericas:
    dados[coluna] = pd.to_numeric(dados[coluna], errors="coerce")

dados

         regiao  total_superior  ...  homens_bem_estar  mulheres_bem_estar
4         Norte         1525166  ...            141169              458616
5      Nordeste         4748933  ...            363905             1458181
6       Sudeste        12828829  ...            768288             2884108
7           Sul         4338861  ...            248574             1007718
8  Centro-Oeste         2412502  ...            156048              593101

[5 rows x 10 columns]

## 6. Confirmar que só temos as 5 grandes regiões

Usamos `isin()` para garantir que ficaram apenas Norte, Nordeste, Sudeste, Sul e Centro-Oeste (sem Brasil, sem estados e sem a linha da fonte).

In [6]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]
dados = dados[dados["regiao"].isin(regioes)]
dados

         regiao  total_superior  ...  homens_bem_estar  mulheres_bem_estar
4         Norte         1525166  ...            141169              458616
5      Nordeste         4748933  ...            363905             1458181
6       Sudeste        12828829  ...            768288             2884108
7           Sul         4338861  ...            248574             1007718
8  Centro-Oeste         2412502  ...            156048              593101

[5 rows x 10 columns]

## 7. Tabela original já tratada

Esta é a tabela `dados`, já com as colunas nomeadas, os valores numéricos convertidos e apenas as 5 grandes regiões.

In [7]:
dados

         regiao  total_superior  ...  homens_bem_estar  mulheres_bem_estar
4         Norte         1525166  ...            141169              458616
5      Nordeste         4748933  ...            363905             1458181
6       Sudeste        12828829  ...            768288             2884108
7           Sul         4338861  ...            248574             1007718
8  Centro-Oeste         2412502  ...            156048              593101

[5 rows x 10 columns]

## 8. Tabela 1 — Homens e mulheres com curso superior completo

In [8]:
tabela_superior = dados[["regiao", "homens_superior", "mulheres_superior"]].copy()
tabela_superior = tabela_superior.rename(columns={
    "regiao": "Regiao",
    "homens_superior": "Homens",
    "mulheres_superior": "Mulheres",
})
tabela_superior = tabela_superior.reset_index(drop=True)
tabela_superior

         Regiao   Homens  Mulheres
0         Norte   590558    934609
1      Nordeste  1744994   3003939
2       Sudeste  5391638   7437191
3           Sul  1768855   2570005
4  Centro-Oeste   982489   1430013

In [9]:
tabela_superior.describe()

             Homens      Mulheres
count  5.000000e+00  5.000000e+00
mean   2.095707e+06  3.075151e+06
std    1.910348e+06  2.577598e+06
min    5.905580e+05  9.346090e+05
25%    9.824890e+05  1.430013e+06
50%    1.744994e+06  2.570005e+06
75%    1.768855e+06  3.003939e+06
max    5.391638e+06  7.437191e+06

## 9. Tabela 2 — Homens e mulheres em Ciência, Tecnologia, Engenharias e Matemática

In [10]:
tabela_ctem = dados[["regiao", "homens_ctem", "mulheres_ctem"]].copy()
tabela_ctem = tabela_ctem.rename(columns={
    "regiao": "Regiao",
    "homens_ctem": "Homens",
    "mulheres_ctem": "Mulheres",
})
tabela_ctem = tabela_ctem.reset_index(drop=True)
tabela_ctem

         Regiao   Homens  Mulheres
0         Norte   133055     76601
1      Nordeste   389993    231395
2       Sudeste  1588874    739247
3           Sul   427372    235543
4  Centro-Oeste   211124    115834

In [11]:
tabela_ctem.describe()

             Homens       Mulheres
count  5.000000e+00       5.000000
mean   5.500836e+05  279724.000000
std    5.934179e+05  266255.481521
min    1.330550e+05   76601.000000
25%    2.111240e+05  115834.000000
50%    3.899930e+05  231395.000000
75%    4.273720e+05  235543.000000
max    1.588874e+06  739247.000000

## 10. Tabela 3 — Homens e mulheres em Educação, Serviços pessoais, Saúde e Bem-estar

In [12]:
tabela_bem_estar = dados[["regiao", "homens_bem_estar", "mulheres_bem_estar"]].copy()
tabela_bem_estar = tabela_bem_estar.rename(columns={
    "regiao": "Regiao",
    "homens_bem_estar": "Homens",
    "mulheres_bem_estar": "Mulheres",
})
tabela_bem_estar = tabela_bem_estar.reset_index(drop=True)
tabela_bem_estar

         Regiao  Homens  Mulheres
0         Norte  141169    458616
1      Nordeste  363905   1458181
2       Sudeste  768288   2884108
3           Sul  248574   1007718
4  Centro-Oeste  156048    593101

In [13]:
tabela_bem_estar.describe()

              Homens      Mulheres
count       5.000000  5.000000e+00
mean   335596.800000  1.280345e+06
std    257699.406993  9.779506e+05
min    141169.000000  4.586160e+05
25%    156048.000000  5.931010e+05
50%    248574.000000  1.007718e+06
75%    363905.000000  1.458181e+06
max    768288.000000  2.884108e+06

## 11. Salvar as três tabelas em arquivos .xlsx

In [14]:
tabela_superior.to_excel("superior_por_regiao_julio.xlsx", index=False)
tabela_ctem.to_excel("ctem_por_regiao_julio.xlsx", index=False)
tabela_bem_estar.to_excel("educacao_saude_bem_estar_julio.xlsx", index=False)

print("Os três arquivos foram salvos com sucesso:")
print("- superior_por_regiao_julio.xlsx")
print("- ctem_por_regiao_julio.xlsx")
print("- educacao_saude_bem_estar_julio.xlsx")

Os três arquivos foram salvos com sucesso:
- superior_por_regiao_julio.xlsx
- ctem_por_regiao_julio.xlsx
- educacao_saude_bem_estar_julio.xlsx

## 12. Gráfico

In [ ]:
%pip install matplotlib seaborn

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
brasil_dados = bruto.iloc[[3]].copy()

brasil_dados.columns = [
    "regiao",
    "total_superior", "homens_superior", "mulheres_superior",
    "total_ctem", "homens_ctem", "mulheres_ctem",
    "total_bem_estar", "homens_bem_estar", "mulheres_bem_estar",
]

for coluna in brasil_dados.columns[1:]:
    brasil_dados[coluna] = pd.to_numeric(brasil_dados[coluna], errors="coerce")

brasil = pd.DataFrame({
    "area": ["Graduação (total)", "STEM", "Saúde / educação"],
    "homens": [
        brasil_dados["homens_superior"].iloc[0],
        brasil_dados["homens_ctem"].iloc[0],
        brasil_dados["homens_bem_estar"].iloc[0]
    ],
    "mulheres": [
        brasil_dados["mulheres_superior"].iloc[0],
        brasil_dados["mulheres_ctem"].iloc[0],
        brasil_dados["mulheres_bem_estar"].iloc[0]
    ]
})

brasil_long = brasil.melt(
    id_vars="area",
    var_name="sexo",
    value_name="pessoas"
)

fig, ax = plt.subplots(figsize=(9, 5))
sns.barplot(data=brasil_long, x="area", y="pessoas", hue="sexo", ax=ax)
ax.set_title("Brasil: pessoas com graduação, por área e sexo")
ax.set_xlabel("Área")
ax.set_ylabel("Pessoas")
plt.tight_layout()
plt.show()