In [5]:
import pandas as pd

In [6]:
t2012 = pd.read_csv("Tabela5-sem_emprego_2012.csv", sep=";", decimal=",")
t2026 = pd.read_csv("Tabela5-sem_emprego_2026.csv", sep=";", decimal=",")

In [7]:
comp = t2012.merge(
    t2026,
    on=["Sigla", "Código", "Estado"],
    how="inner"
)

comp["Variação homens (p.p.)"] = (
    comp["Desocupados - homens (2026 T1)"] -
    comp["Desocupados - homens (2012 T1)"]
)

comp["Variação mulheres (p.p.)"] = (
    comp["Desocupados - mulheres (2026 T1)"] -
    comp["Desocupados - mulheres (2012 T1)"]
)

comp

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Variação homens (p.p.),Variação mulheres (p.p.)
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7
3,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3
13,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8
16,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9
17,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1

In [8]:
bruto = pd.read_excel("Tabela 1.1.1.xls", sheet_name="2022", header=None)

horas = bruto.iloc[8:41, [0, 1, 4, 5, 6, 7]].copy()

horas.columns = [
    "Estado",
    "Horas totais (2022)",
    "Horas homens brancos (2022)",
    "Horas homens pretos ou pardos (2022)",
    "Horas mulheres brancas (2022)",
    "Horas mulheres pretas ou pardas (2022)"
]

horas = horas[horas["Estado"].isin(comp["Estado"])].copy()

colunas_horas = horas.columns[1:]
horas[colunas_horas] = horas[colunas_horas].apply(
    pd.to_numeric,
    errors="coerce"
)

horas

,Estado,Horas totais (2022),Horas homens brancos (2022),Horas homens pretos ou pardos (2022),Horas mulheres brancas (2022),Horas mulheres pretas ou pardas (2022)
10,Rondônia,17.014162,12.111127,12.544080,20.412887,21.061410
11,Acre,13.606903,10.796120,9.686983,16.130352,16.710754
12,Amazonas,16.807290,12.233043,12.822584,18.764969,20.716986
13,Roraima,13.639257,10.814803,10.476601,16.135877,16.560244
14,Pará,16.474268,11.524306,11.026707,19.835110,21.591144
15,Amapá,13.586656,11.116821,10.749444,16.648579,15.908487
16,Tocantins,15.815781,10.733863,11.682616,19.663713,19.629399
18,Maranhão,16.669614,11.665173,11.437359,19.881056,20.739589
19,Piauí,17.960366,12.258324,11.204814,20.494063,23.695440
20,Ceará,19.499293,12.186936,12.821323,23.019718,24.952274
21,Rio Grande do Norte,18.307740,11.166909,11.086286,23.547080,24.422884
22,Paraíba,18.920816,12.480204,12.400831,23.642936,24.035650
23,Pernambuco,19.306249,12.312833,12.868821,23.357880,24.243396
24,Alagoas,20.217129,12.121839,13.357160,24.093655,25.856637
25,Sergipe,18.826541,10.830511,11.270341,21.740902,25.637681
26,Bahia,17.849776,10.551673,10.982808,22.572730,23.217119
28,Minas Gerais,17.502141,11.319720,11.619120,22.186650,23.075751
29,Espírito Santo,17.111106,11.798571,12.017589,20.464462,22.196626
30,Rio de Janeiro,16.716263,12.000036,12.864896,19.203741,20.957728
31,São Paulo,17.071295,12.123044,12.235200,20.771186,21.767620
33,Paraná,15.390122,11.240085,10.815611,18.896661,19.365380
34,Santa Catarina,16.039355,12.339052,11.517342,19.414764,19.646573
35,Rio Grande do Sul,15.356709,11.308447,11.519941,18.868230,19.107720
37,Mato Grosso do Sul,15.309783,10.446213,11.126920,18.593200,19.542761
38,Mato Grosso,14.239989,9.479654,9.265734,17.782825,18.695923
39,Goiás,15.186471,10.636424,10.531883,18.440842,19.587913
40,Distrito Federal,15.096351,11.377952,10.481279,17.738123,19.307332

In [9]:
cruzado = comp.merge(horas, on="Estado", how="inner")

cruzado

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Variação homens (p.p.),Variação mulheres (p.p.),Horas totais (2022),Horas homens brancos (2022),Horas homens pretos ou pardos (2022),Horas mulheres brancas (2022),Horas mulheres pretas ou pardas (2022)
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9,13.606903,10.796120,9.686983,16.130352,16.710754
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0,20.217129,12.121839,13.357160,24.093655,25.856637
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7,16.807290,12.233043,12.822584,18.764969,20.716986
3,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0,13.586656,11.116821,10.749444,16.648579,15.908487
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9,17.849776,10.551673,10.982808,22.572730,23.217119
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6,19.499293,12.186936,12.821323,23.019718,24.952274
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9,15.096351,11.377952,10.481279,17.738123,19.307332
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1,17.111106,11.798571,12.017589,20.464462,22.196626
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5,15.186471,10.636424,10.531883,18.440842,19.587913
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9,16.669614,11.665173,11.437359,19.881056,20.739589
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5,17.502141,11.319720,11.619120,22.186650,23.075751
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9,15.309783,10.446213,11.126920,18.593200,19.542761
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3,14.239989,9.479654,9.265734,17.782825,18.695923
13,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1,16.474268,11.524306,11.026707,19.835110,21.591144
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5,18.920816,12.480204,12.400831,23.642936,24.035650
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8,19.306249,12.312833,12.868821,23.357880,24.243396
16,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9,17.960366,12.258324,11.204814,20.494063,23.695440
17,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0,15.390122,11.240085,10.815611,18.896661,19.365380
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2,16.716263,12.000036,12.864896,19.203741,20.957728
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8,18.307740,11.166909,11.086286,23.547080,24.422884
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4,17.014162,12.111127,12.544080,20.412887,21.061410
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6,13.639257,10.814803,10.476601,16.135877,16.560244
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6,15.356709,11.308447,11.519941,18.868230,19.107720
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9,16.039355,12.339052,11.517342,19.414764,19.646573
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2,18.826541,10.830511,11.270341,21.740902,25.637681
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8,17.071295,12.123044,12.235200,20.771186,21.767620
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1,15.815781,10.733863,11.682616,19.663713,19.629399

In [10]:
cruzado.to_csv("geral.csv", sep=";", decimal=",", index=False)

print(f"{cruzado.shape[0]} estados incluídos em geral.csv")

27 estados incluídos em geral.csv